version: '3.8'


networks:
  webnetwork:

services:
  webserver:
    networks:
      - webnetwork
    container_name: brandless-web-backend
    build:
      context: ../
      dockerfile: ./dev/Dockerfile.webserver
    ports:
      - "4000:4000"
    volumes:
      - ../web-server:/project/app
    restart: on-failure
  db:
    networks:
      - webnetwork
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local