// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Connection interface {
	IsConnection()
}

type Edge interface {
	IsEdge()
}

type Node interface {
	IsNode()
}

type Brand struct {
	ID       string             `json:"id"`
	Name     string             `json:"name"`
	Logo     string             `json:"logo"`
	Products *ProductConnection `json:"products"`
}

func (Brand) IsNode() {}

type BrandConnection struct {
	TotalCount int          `json:"totalCount"`
	PageInfo   *PageInfo    `json:"pageInfo"`
	Edges      []*BrandEdge `json:"edges"`
}

func (BrandConnection) IsConnection() {}

type BrandEdge struct {
	Node   *Brand `json:"node"`
	Cursor string `json:"cursor"`
}

func (BrandEdge) IsEdge() {}

type Comment struct {
	ID        string   `json:"id"`
	Media     []string `json:"media"`
	Content   string   `json:"content"`
	CreatedAt string   `json:"createdAt"`
}

func (Comment) IsNode() {}

type CommentConnection struct {
	TotalCount int            `json:"totalCount"`
	PageInfo   *PageInfo      `json:"pageInfo"`
	Edges      []*CommentEdge `json:"edges"`
}

func (CommentConnection) IsConnection() {}

type CommentEdge struct {
	Node   *Comment `json:"node"`
	Cursor string   `json:"cursor"`
}

func (CommentEdge) IsEdge() {}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor"`
	EndCursor       *string `json:"endCursor"`
}

type Product struct {
	ID        string             `json:"id"`
	ProductID string             `json:"productId"`
	Name      string             `json:"name"`
	Link      string             `json:"link"`
	Brand     *Brand             `json:"brand"`
	BrandID   string             `json:"brandId"`
	Images    []string           `json:"images"`
	Reviews   *CommentConnection `json:"reviews"`
	CreatedAt string             `json:"createdAt"`
}

func (Product) IsNode() {}

type ProductConnection struct {
	TotalCount int            `json:"totalCount"`
	PageInfo   *PageInfo      `json:"pageInfo"`
	Edges      []*ProductEdge `json:"edges"`
}

func (ProductConnection) IsConnection() {}

type ProductEdge struct {
	Node   *Product `json:"node"`
	Cursor string   `json:"cursor"`
}

func (ProductEdge) IsEdge() {}
