// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: admin-apis.proto

package adminapis

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdminAPIServiceClient is the client API for AdminAPIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminAPIServiceClient interface {
	PullProducts(ctx context.Context, in *PullProductsRequest, opts ...grpc.CallOption) (*PullProductsResponse, error)
}

type adminAPIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminAPIServiceClient(cc grpc.ClientConnInterface) AdminAPIServiceClient {
	return &adminAPIServiceClient{cc}
}

func (c *adminAPIServiceClient) PullProducts(ctx context.Context, in *PullProductsRequest, opts ...grpc.CallOption) (*PullProductsResponse, error) {
	out := new(PullProductsResponse)
	err := c.cc.Invoke(ctx, "/AdminAPIService/pullProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminAPIServiceServer is the server API for AdminAPIService service.
// All implementations must embed UnimplementedAdminAPIServiceServer
// for forward compatibility
type AdminAPIServiceServer interface {
	PullProducts(context.Context, *PullProductsRequest) (*PullProductsResponse, error)
	mustEmbedUnimplementedAdminAPIServiceServer()
}

// UnimplementedAdminAPIServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAdminAPIServiceServer struct {
}

func (UnimplementedAdminAPIServiceServer) PullProducts(context.Context, *PullProductsRequest) (*PullProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullProducts not implemented")
}
func (UnimplementedAdminAPIServiceServer) mustEmbedUnimplementedAdminAPIServiceServer() {}

// UnsafeAdminAPIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminAPIServiceServer will
// result in compilation errors.
type UnsafeAdminAPIServiceServer interface {
	mustEmbedUnimplementedAdminAPIServiceServer()
}

func RegisterAdminAPIServiceServer(s grpc.ServiceRegistrar, srv AdminAPIServiceServer) {
	s.RegisterService(&AdminAPIService_ServiceDesc, srv)
}

func _AdminAPIService_PullProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminAPIServiceServer).PullProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AdminAPIService/pullProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminAPIServiceServer).PullProducts(ctx, req.(*PullProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminAPIService_ServiceDesc is the grpc.ServiceDesc for AdminAPIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminAPIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AdminAPIService",
	HandlerType: (*AdminAPIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "pullProducts",
			Handler:    _AdminAPIService_PullProducts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin-apis.proto",
}
